/**
 * Pure (no three.js, no animation) 3x3 cube model made of 54 stickers.
 *
 * Every sticker is described geometrically (cubie position + face normal), so all
 * move permutations are generated by rotating those vectors instead of being typed
 * in by hand. This also lets us support wide moves, slices and cube rotations.
 *
 * Axes: +x = Right, +y = Up, +z = Front.
 * Sticker index = faceIndex * 9 + row * 3 + col, faces ordered U R F D L B and
 * every face is laid out like the standard cube net (looking at the face from outside).
 */

export type Color = 'W' | 'Y' | 'R' | 'O' | 'G' | 'B';
export type FaceLetter = 'U' | 'R' | 'F' | 'D' | 'L' | 'B';
export type Vec3 = [number, number, number];

export const FACES: FaceLetter[] = ['U', 'R', 'F', 'D', 'L', 'B'];

/** Yellow on top, red in front (same orientation the scanner asks for). */
export const FACE_COLOR: Record<FaceLetter, Color> = {
  U: 'Y', R: 'G', F: 'R', D: 'W', L: 'B', B: 'O',
};

export const FACE_NORMAL: Record<FaceLetter, Vec3> = {
  U: [0, 1, 0], R: [1, 0, 0], F: [0, 0, 1], D: [0, -1, 0], L: [-1, 0, 0], B: [0, 0, -1],
};

/** Cubie position of the sticker at (row, col) of a face in standard net layout. */
function netPosition(face: FaceLetter, r: number, c: number): Vec3 {
  switch (face) {
    case 'U': return [c - 1, 1, r - 1];
    case 'R': return [1, 1 - r, 1 - c];
    case 'F': return [c - 1, 1 - r, 1];
    case 'D': return [c - 1, -1, 1 - r];
    case 'L': return [-1, 1 - r, c - 1];
    case 'B': return [1 - c, 1 - r, -1];
  }
}

export const STICKER_POS: Vec3[] = [];
export const STICKER_NORMAL: Vec3[] = [];
export const STICKER_FACE: FaceLetter[] = [];
const keyOf = (p: Vec3, n: Vec3) => `${p.join(',')}|${n.join(',')}`;
const stickerByKey = new Map<string, number>();

FACES.forEach((face) => {
  for (let r = 0; r < 3; r++) {
    for (let c = 0; c < 3; c++) {
      const idx = STICKER_POS.length;
      const pos = netPosition(face, r, c);
      STICKER_POS.push(pos);
      STICKER_NORMAL.push(FACE_NORMAL[face]);
      STICKER_FACE.push(face);
      stickerByKey.set(keyOf(pos, FACE_NORMAL[face]), idx);
    }
  }
});

export const stickerIndex = (pos: Vec3, normal: Vec3) => stickerByKey.get(keyOf(pos, normal))!;

/** Sticker index by cubie position and face, e.g. stickerAt([1,1,1], 'U'). */
export const stickerAt = (pos: Vec3, face: FaceLetter) => stickerIndex(pos, FACE_NORMAL[face]);

export const SOLVED: Color[] = STICKER_FACE.map((f) => FACE_COLOR[f]);

// ---------------------------------------------------------------------------
// vector helpers
// ---------------------------------------------------------------------------

const dot = (a: Vec3, b: Vec3) => a[0] * b[0] + a[1] * b[1] + a[2] * b[2];
const cross = (a: Vec3, b: Vec3): Vec3 => [
  a[1] * b[2] - a[2] * b[1],
  a[2] * b[0] - a[0] * b[2],
  a[0] * b[1] - a[1] * b[0],
];
const scale = (a: Vec3, s: number): Vec3 => [a[0] * s, a[1] * s, a[2] * s];
const add = (a: Vec3, b: Vec3): Vec3 => [a[0] + b[0], a[1] + b[1], a[2] + b[2]];
const norm0 = (a: Vec3): Vec3 => [a[0] || 0, a[1] || 0, a[2] || 0]; // avoid -0

/** Rotate v by 90 degrees about unit axis n. dir = -1 is clockwise seen from the tip of n. */
function rotate90(v: Vec3, n: Vec3, dir: 1 | -1): Vec3 {
  // v' = dir * (n x v) + n (n . v)
  return norm0(add(scale(cross(n, v), dir), scale(n, dot(n, v))));
}

// ---------------------------------------------------------------------------
// moves
// ---------------------------------------------------------------------------

/** Turn `layers` (values of n . pos) about axis n, `turns` quarter turns clockwise seen from n. */
export interface MoveSpec {
  axis: Vec3;
  layers: number[];
  turns: number; // 1..3
}

/** gather permutation: newState[i] = oldState[perm[i]] */
function buildGather(spec: MoveSpec): number[] {
  const gather = STICKER_POS.map((_, i) => i);
  for (let i = 0; i < 54; i++) {
    if (!spec.layers.includes(dot(STICKER_POS[i], spec.axis))) continue;
    let p = STICKER_POS[i];
    let n = STICKER_NORMAL[i];
    for (let t = 0; t < spec.turns; t++) {
      p = rotate90(p, spec.axis, -1);
      n = rotate90(n, spec.axis, -1);
    }
    gather[stickerIndex(p, n)] = i;
  }
  return gather;
}

interface BaseMove { axis: Vec3; layers: number[] }

const BASE_MOVES: Record<string, BaseMove> = {
  U: { axis: [0, 1, 0], layers: [1] },
  D: { axis: [0, -1, 0], layers: [1] },
  R: { axis: [1, 0, 0], layers: [1] },
  L: { axis: [-1, 0, 0], layers: [1] },
  F: { axis: [0, 0, 1], layers: [1] },
  B: { axis: [0, 0, -1], layers: [1] },
  u: { axis: [0, 1, 0], layers: [0, 1] },
  d: { axis: [0, -1, 0], layers: [0, 1] },
  r: { axis: [1, 0, 0], layers: [0, 1] },
  l: { axis: [-1, 0, 0], layers: [0, 1] },
  f: { axis: [0, 0, 1], layers: [0, 1] },
  b: { axis: [0, 0, -1], layers: [0, 1] },
  M: { axis: [-1, 0, 0], layers: [0] },
  E: { axis: [0, -1, 0], layers: [0] },
  S: { axis: [0, 0, 1], layers: [0] },
  x: { axis: [1, 0, 0], layers: [-1, 0, 1] },
  y: { axis: [0, 1, 0], layers: [-1, 0, 1] },
  z: { axis: [0, 0, 1], layers: [-1, 0, 1] },
};

// Canonical notation of a move given the positive axis it acts on and the layer coordinates it covers.
// `flip` = the notation turns clockwise about the negative axis.
const CANONICAL: Record<number, Record<string, { name: string; flip: boolean }>> = {
  0: { '1': { name: 'R', flip: false }, '-1': { name: 'L', flip: true }, '0,1': { name: 'r', flip: false }, '-1,0': { name: 'l', flip: true }, '0': { name: 'M', flip: true } },
  1: { '1': { name: 'U', flip: false }, '-1': { name: 'D', flip: true }, '0,1': { name: 'u', flip: false }, '-1,0': { name: 'd', flip: true }, '0': { name: 'E', flip: true } },
  2: { '1': { name: 'F', flip: false }, '-1': { name: 'B', flip: true }, '0,1': { name: 'f', flip: false }, '-1,0': { name: 'b', flip: true }, '0': { name: 'S', flip: false } },
};

type Mat = [Vec3, Vec3, Vec3]; // rows
const IDENTITY: Mat = [[1, 0, 0], [0, 1, 0], [0, 0, 1]];
const matVec = (m: Mat, v: Vec3): Vec3 => norm0([dot(m[0], v), dot(m[1], v), dot(m[2], v)]);
/** Matrix of the +90 degree rotation about unit axis n. */
function rotationMatrix(n: Vec3): Mat {
  const col = (e: Vec3) => rotate90(e, n, 1);
  const cx = col([1, 0, 0]), cy = col([0, 1, 0]), cz = col([0, 0, 1]);
  return [[cx[0], cy[0], cz[0]], [cx[1], cy[1], cz[1]], [cx[2], cy[2], cz[2]]];
}
/** a * b (apply b first). */
function matMul(a: Mat, b: Mat): Mat {
  const cols = [0, 1, 2].map((j) => matVec(a, [b[0][j], b[1][j], b[2][j]]));
  return [[cols[0][0], cols[1][0], cols[2][0]], [cols[0][1], cols[1][1], cols[2][1]], [cols[0][2], cols[1][2], cols[2][2]]];
}

const TOKEN_RE = /^([URFDLBurfdlbMESxyz])(2'|'2|2|')?$/;

/** Split an algorithm string into tokens. Parentheses only group; "(R U)2" repeats the group. */
export function tokenize(alg: string): string[] {
  const expanded = alg.replace(/\(([^()]*)\)(\d?)/g, (_, body: string, times: string) =>
    Array.from({ length: Number(times) || 1 }, () => body).join(' '));
  return expanded.replace(/[()]/g, ' ').split(/\s+/).filter(Boolean);
}

function tokenTurns(suffix: string | undefined): number {
  if (!suffix) return 1;
  if (suffix === "'") return 3;
  return 2;
}

/**
 * Convert any algorithm (wide moves, slices, x/y/z rotations allowed) into an
 * equivalent list of moves that acts on the fixed cube and needs no rotation.
 * Rotations only change how the following moves are interpreted.
 */
export function normalizeAlg(alg: string | string[]): string[] {
  const tokens = Array.isArray(alg) ? alg : tokenize(alg);
  let frame: Mat = IDENTITY;
  const out: string[] = [];
  for (const token of tokens) {
    const m = TOKEN_RE.exec(token);
    if (!m) throw new Error(`Invalid move "${token}"`);
    const base = BASE_MOVES[m[1]];
    const turns = tokenTurns(m[2]);
    if ('xyz'.includes(m[1])) {
      // viewing direction rotates, so following moves are seen through the inverse rotation
      const rot = rotationMatrix(base.axis);
      for (let t = 0; t < turns; t++) frame = matMul(frame, rot);
      continue;
    }
    const axis = matVec(frame, base.axis);
    const axisIdx = axis.findIndex((v) => v !== 0);
    const positive = axis[axisIdx] > 0;
    const coords = (positive ? base.layers : base.layers.map((l) => -l || 0)).slice().sort((a, b) => a - b);
    const canon = CANONICAL[axisIdx][coords.join(',')];
    if (!canon) throw new Error(`Cannot name move "${token}"`);
    // rotation about +axis by `turns` clockwise quarter turns
    const signedTurns = positive ? turns : 4 - turns;
    const finalTurns = canon.flip ? (4 - signedTurns) % 4 : signedTurns % 4;
    out.push(canon.name + ['', '', '2', "'"][finalTurns]);
  }
  return out;
}

const gatherCache = new Map<string, number[]>();

/** Permutation of a rotation-free single move token. */
export function moveGather(token: string): number[] {
  let g = gatherCache.get(token);
  if (!g) {
    const m = TOKEN_RE.exec(token);
    if (!m || 'xyz'.includes(m[1])) throw new Error(`Invalid move "${token}"`);
    const base = BASE_MOVES[m[1]];
    g = buildGather({ axis: base.axis, layers: base.layers, turns: tokenTurns(m[2]) });
    gatherCache.set(token, g);
  }
  return g;
}

/** Where a sticker ends up after the move: forward[i] = j means sticker i moves to slot j. */
const forwardCache = new Map<string, number[]>();
export function moveForward(token: string): number[] {
  let f = forwardCache.get(token);
  if (!f) {
    const g = moveGather(token);
    f = new Array(54);
    g.forEach((from, to) => { f![from] = to; });
    forwardCache.set(token, f);
  }
  return f;
}

const rotationCache = new Map<string, number[]>();

/** Whole cube rotation (x, y, z with optional ' or 2) applied to a state, centers included. */
export function rotateState<T>(state: readonly T[], token: string): T[] {
  let g = rotationCache.get(token);
  if (!g) {
    const m = TOKEN_RE.exec(token);
    if (!m || !'xyz'.includes(m[1])) throw new Error(`Invalid rotation "${token}"`);
    const base = BASE_MOVES[m[1]];
    g = buildGather({ axis: base.axis, layers: base.layers, turns: tokenTurns(m[2]) });
    rotationCache.set(token, g);
  }
  return g.map((from) => state[from]);
}

export const ROTATIONS = ['x', "x'", 'x2', 'y', "y'", 'y2', 'z', "z'", 'z2'];

export function applyMove<T>(state: readonly T[], token: string): T[] {
  const g = moveGather(token);
  return g.map((from) => state[from]);
}

/** Apply an algorithm (any supported notation) to a state. */
export function applyAlg<T>(state: readonly T[], alg: string | string[]): T[] {
  let s = state as T[];
  for (const token of normalizeAlg(alg)) s = applyMove(s, token);
  return s;
}

/** Notation of the inverse of a rotation-free move list. */
export function invertAlg(tokens: string[]): string[] {
  return tokens.slice().reverse().map((t) => {
    if (t.endsWith('2')) return t;
    return t.endsWith("'") ? t.slice(0, -1) : t + "'";
  });
}

export function isSolved(state: readonly Color[]): boolean {
  return state.every((c, i) => c === SOLVED[i]);
}

/** Solved, but the whole cube may be held in another orientation. */
export function isSolvedAnyOrientation(state: readonly Color[]): boolean {
  return state.every((c, i) => c === state[Math.floor(i / 9) * 9 + 4]);
}

export const centersHome = (state: readonly Color[]) => FACES.every((f, i) => state[i * 9 + 4] === FACE_COLOR[f]);

/** The 18 outer-layer moves used by the searches. */
export const FACE_MOVES: string[] = FACES.flatMap((f) => [f, f + '2', f + "'"]);

// ---------------------------------------------------------------------------
// cubies
// ---------------------------------------------------------------------------

/** Stickers of the cubie at `pos`, i.e. every sticker sharing that position. */
const cubieStickers = new Map<string, number[]>();
STICKER_POS.forEach((p, i) => {
  const k = p.join(',');
  if (!cubieStickers.has(k)) cubieStickers.set(k, []);
  cubieStickers.get(k)!.push(i);
});

/** All stickers of the same cubie as sticker i (including i). */
export const cubieOf = (i: number): number[] => cubieStickers.get(STICKER_POS[i].join(','))!;

export const cubieType = (i: number): 'center' | 'edge' | 'corner' =>
  (['center', 'edge', 'corner'] as const)[cubieOf(i).length - 1];

/**
 * Current position of the piece that lives at sticker `home` in the solved cube:
 * returns the sticker index that carries the same color, on the cubie that holds all its colors.
 */
export function locatePiece(state: readonly Color[], home: number): number {
  const colors = cubieOf(home).map((s) => SOLVED[s]);
  const want = SOLVED[home];
  for (const [, stickers] of cubieStickers) {
    if (stickers.length !== colors.length) continue;
    if (!colors.every((c) => stickers.some((s) => state[s] === c))) continue;
    return stickers.find((s) => state[s] === want)!;
  }
  return -1;
}

// ---------------------------------------------------------------------------
// validation
// ---------------------------------------------------------------------------

// Orientation reference: the sticker on the U/D face, else on the F/B face.
const refRank = (i: number) => ({ U: 0, D: 0, F: 1, B: 1, R: 2, L: 2 })[STICKER_FACE[i]];

/** Right-handed ordering of the stickers of a corner cubie, starting from its U/D sticker. */
function orderedCorner(stickers: number[]): number[] {
  const [a, b, c] = stickers;
  const tri = dot(cross(STICKER_NORMAL[a], STICKER_NORMAL[b]), STICKER_NORMAL[c]);
  const cyc = tri > 0 ? [a, b, c] : [a, c, b];
  const start = cyc.findIndex((s) => refRank(s) === 0);
  return [...cyc.slice(start), ...cyc.slice(0, start)];
}

const cornerCubies = [...cubieStickers.values()].filter((s) => s.length === 3).map(orderedCorner);
const edgeCubies = [...cubieStickers.values()]
  .filter((s) => s.length === 2)
  .map((s) => s.slice().sort((a, b) => refRank(a) - refRank(b)));
const colorKey = (cols: Color[]) => cols.slice().sort().join('');

const cornerHome = new Map(cornerCubies.map((s, i) => [colorKey(s.map((x) => SOLVED[x])), i]));
const edgeHome = new Map(edgeCubies.map((s, i) => [colorKey(s.map((x) => SOLVED[x])), i]));

function parity(perm: number[]): number {
  let inversions = 0;
  for (let i = 0; i < perm.length; i++) {
    for (let j = i + 1; j < perm.length; j++) if (perm[i] > perm[j]) inversions++;
  }
  return inversions % 2;
}

/** Returns a human readable reason why the state cannot be solved, or null when it is valid. */
export function validateState(state: readonly Color[]): string | null {
  for (const face of FACES) {
    const center = state[FACES.indexOf(face) * 9 + 4];
    if (center !== FACE_COLOR[face]) {
      return `Center of ${face} face must be ${FACE_COLOR[face]} but is ${center}. Hold the cube yellow on top and red in front.`;
    }
  }

  const cornerPerm: number[] = [];
  let twist = 0;
  const seenCorner = new Set<number>();
  for (const stickers of cornerCubies) {
    const cols = stickers.map((s) => state[s]);
    const home = cornerHome.get(colorKey(cols));
    if (home === undefined || seenCorner.has(home)) return 'Some corner pieces are impossible (duplicate or invalid colors combination).';
    seenCorner.add(home);
    // orientation: which sticker of the piece carries the U/D color
    const homeCols = cornerCubies[home].map((s) => SOLVED[s]);
    const shift = cols.findIndex((c) => c === homeCols[0]);
    // check chirality (cyclic order must match)
    if (cols[(shift + 1) % 3] !== homeCols[1] || cols[(shift + 2) % 3] !== homeCols[2]) {
      return 'A corner piece is mirrored — one of the scanned colors is wrong.';
    }
    twist += shift;
    cornerPerm.push(home);
  }
  if (twist % 3 !== 0) return 'A corner is twisted in place — the cube is not solvable, check the scanned colors.';

  const edgePerm: number[] = [];
  let flip = 0;
  const seenEdge = new Set<number>();
  for (const stickers of edgeCubies) {
    const cols = stickers.map((s) => state[s]);
    const home = edgeHome.get(colorKey(cols));
    if (home === undefined || seenEdge.has(home)) return 'Some edge pieces are impossible (duplicate or invalid colors combination).';
    seenEdge.add(home);
    if (cols[0] !== SOLVED[edgeCubies[home][0]]) flip++;
    edgePerm.push(home);
  }
  if (flip % 2 !== 0) return 'An edge is flipped in place — the cube is not solvable, check the scanned colors.';

  if (parity(cornerPerm) !== parity(edgePerm)) return 'Two pieces are swapped — the cube is not solvable, check the scanned colors.';
  return null;
}
