/**
 * The 41 F2L cases of the front-right slot (white cross on the bottom, yellow on top, red in front).
 * GENERATED by src/solver/__tests__/f2lCases.generate.test.ts, do not edit by hand.
 *
 *  setup:          moves that make the case from a solved cube
 *  algorithms:     algorithms that solve it; from the dictionary (f2l.algo.ts) when one fits
 *  fromDictionary: dictionary entries that solve this case
 *  generated:      shortest algorithm found by search (R/U first, then F, then L/B)
 */
export interface F2lCase {
  id: number
  group: 'both-top' | 'edge-in-slot' | 'corner-in-slot' | 'both-in-slot'
  setup: string
  algorithms: string[]
  fromDictionary: string[]
  generated: string
}

export const F2L_CASES: F2lCase[] = [
  {
    "id": 1,
    "group": "both-top",
    "setup": "R U' R'",
    "algorithms": [
      "R U R'"
    ],
    "fromDictionary": [
      "c20e10",
      "c21e30"
    ],
    "generated": "R U R'"
  },
  {
    "id": 2,
    "group": "both-top",
    "setup": "F' U2 F",
    "algorithms": [
      "F' U2 F"
    ],
    "fromDictionary": [],
    "generated": "F' U2 F"
  },
  {
    "id": 3,
    "group": "both-top",
    "setup": "R U R'",
    "algorithms": [
      "R U' R'"
    ],
    "fromDictionary": [
      "basic-paired",
      "c00e10"
    ],
    "generated": "R U' R'"
  },
  {
    "id": 4,
    "group": "both-top",
    "setup": "F' U F",
    "algorithms": [
      "F' U' F"
    ],
    "fromDictionary": [],
    "generated": "F' U' F"
  },
  {
    "id": 5,
    "group": "both-top",
    "setup": "F' U F R U' R'",
    "algorithms": [
      "R U R' F' U' F"
    ],
    "fromDictionary": [],
    "generated": "R U R' F' U' F"
  },
  {
    "id": 6,
    "group": "both-top",
    "setup": "R U R' U' R U' R'",
    "algorithms": [
      "R U R' U R U' R'"
    ],
    "fromDictionary": [
      "c10e10",
      "c00e20",
      "c30e10"
    ],
    "generated": "R U R' U R U' R'"
  },
  {
    "id": 7,
    "group": "both-top",
    "setup": "R' F R F2 U2 F",
    "algorithms": [
      "F' U2 F2 R' F' R"
    ],
    "fromDictionary": [],
    "generated": "F' U2 F2 R' F' R"
  },
  {
    "id": 8,
    "group": "both-top",
    "setup": "R U' R' U R U2 R'",
    "algorithms": [
      "R U2 R' U' R U R'"
    ],
    "fromDictionary": [
      "c20e00",
      "c21e20",
      "c11e10",
      "c01e00",
      "corner-in-slot-edge-ul"
    ],
    "generated": "R U2 R' U' R U R'"
  },
  {
    "id": 9,
    "group": "both-top",
    "setup": "R U R' U' R U2 R'",
    "algorithms": [
      "R U2 R' U R U' R'"
    ],
    "fromDictionary": [
      "c20e20",
      "c21e00",
      "separated-3"
    ],
    "generated": "R U2 R' U R U' R'"
  },
  {
    "id": 10,
    "group": "both-top",
    "setup": "F2 U' F U' F' U2 F2",
    "algorithms": [
      "F2 U2 F U F' U F2"
    ],
    "fromDictionary": [],
    "generated": "F2 U2 F U F' U F2"
  },
  {
    "id": 11,
    "group": "both-top",
    "setup": "R U' R' U R U R'",
    "algorithms": [
      "R U' R' U' R U R'"
    ],
    "fromDictionary": [
      "c10e20",
      "c00e00",
      "c30e00",
      "corner-in-slot-edge-uf"
    ],
    "generated": "R U' R' U' R U R'"
  },
  {
    "id": 12,
    "group": "both-top",
    "setup": "R2 U2 R' U' R U' R2",
    "algorithms": [
      "R2 U R' U R U2 R2"
    ],
    "fromDictionary": [],
    "generated": "R2 U R' U R U2 R2"
  },
  {
    "id": 13,
    "group": "both-top",
    "setup": "R' U' R2 U' R2 U2 R",
    "algorithms": [
      "U2 R U2 R' U' R U R' U' R U R'",
      "R' U2 R2 U R2 U R"
    ],
    "fromDictionary": [
      "slot-wrong-ori-3"
    ],
    "generated": "R' U2 R2 U R2 U R"
  },
  {
    "id": 14,
    "group": "both-top",
    "setup": "F' U2 F U' F' U F",
    "algorithms": [
      "F' U' F U F' U2 F"
    ],
    "fromDictionary": [],
    "generated": "F' U' F U F' U2 F"
  },
  {
    "id": 15,
    "group": "both-top",
    "setup": "R U R' U2 R U' R'",
    "algorithms": [
      "R U R' U2 R U' R'"
    ],
    "fromDictionary": [],
    "generated": "R U R' U2 R U' R'"
  },
  {
    "id": 16,
    "group": "both-top",
    "setup": "F' U F U F' U' F",
    "algorithms": [
      "F' U F U' F' U' F"
    ],
    "fromDictionary": [],
    "generated": "F' U F U' F' U' F"
  },
  {
    "id": 17,
    "group": "both-top",
    "setup": "F' U F U' R U R'",
    "algorithms": [
      "R U' R' U F' U' F"
    ],
    "fromDictionary": [],
    "generated": "R U' R' U F' U' F"
  },
  {
    "id": 18,
    "group": "both-top",
    "setup": "F' U F U' R U2 R'",
    "algorithms": [
      "R U2 R' U F' U' F"
    ],
    "fromDictionary": [],
    "generated": "R U2 R' U F' U' F"
  },
  {
    "id": 19,
    "group": "both-top",
    "setup": "F' U F U2 R U R'",
    "algorithms": [
      "R U' R' U2 F' U' F"
    ],
    "fromDictionary": [],
    "generated": "R U' R' U2 F' U' F"
  },
  {
    "id": 20,
    "group": "both-top",
    "setup": "R U R' U2 R U2 R'",
    "algorithms": [
      "R U2 R' U2 R U' R'"
    ],
    "fromDictionary": [],
    "generated": "R U2 R' U2 R U' R'"
  },
  {
    "id": 21,
    "group": "both-top",
    "setup": "R2 U R' U R U2 R2",
    "algorithms": [
      "R2 U2 R' U' R U' R2"
    ],
    "fromDictionary": [],
    "generated": "R2 U2 R' U' R U' R2"
  },
  {
    "id": 22,
    "group": "both-top",
    "setup": "F2 U2 R' F R U2 F2",
    "algorithms": [
      "F2 U2 R' F' R U2 F2"
    ],
    "fromDictionary": [],
    "generated": "F2 U2 R' F' R U2 F2"
  },
  {
    "id": 23,
    "group": "both-top",
    "setup": "R2 U2 F R2 F' U2 R2",
    "algorithms": [
      "R2 U2 F R2 F' U2 R2"
    ],
    "fromDictionary": [],
    "generated": "R2 U2 F R2 F' U2 R2"
  },
  {
    "id": 24,
    "group": "both-top",
    "setup": "R2 U2 R U' R U R' U2 R2",
    "algorithms": [
      "R2 U2 R U' R' U R' U2 R2"
    ],
    "fromDictionary": [],
    "generated": "R2 U2 R U' R' U R' U2 R2"
  },
  {
    "id": 25,
    "group": "edge-in-slot",
    "setup": "R U' R' F' U2 F",
    "algorithms": [
      "F' U2 F R U R'"
    ],
    "fromDictionary": [],
    "generated": "F' U2 F R U R'"
  },
  {
    "id": 26,
    "group": "edge-in-slot",
    "setup": "R U' R' U2 R U' R'",
    "algorithms": [
      "R U R' U2 R U R'"
    ],
    "fromDictionary": [],
    "generated": "R U R' U2 R U R'"
  },
  {
    "id": 27,
    "group": "edge-in-slot",
    "setup": "F' U F U' R U' R'",
    "algorithms": [
      "R U R' U F' U' F"
    ],
    "fromDictionary": [],
    "generated": "R U R' U F' U' F"
  },
  {
    "id": 28,
    "group": "edge-in-slot",
    "setup": "R U' R' U F' U F",
    "algorithms": [
      "F' U' F U' R U R'"
    ],
    "fromDictionary": [],
    "generated": "F' U' F U' R U R'"
  },
  {
    "id": 29,
    "group": "edge-in-slot",
    "setup": "R U R' U2 R U R'",
    "algorithms": [
      "R U' R' U2 R U' R'"
    ],
    "fromDictionary": [
      "c31e20"
    ],
    "generated": "R U' R' U2 R U' R'"
  },
  {
    "id": 30,
    "group": "edge-in-slot",
    "setup": "R2 U R2 U R2 U2 R2",
    "algorithms": [
      "U2 R U R' U' R U R' U' R U R'",
      "R2 U2 R2 U' R2 U' R2"
    ],
    "fromDictionary": [
      "c30e20",
      "edge-flip-2",
      "slot-wrong-ori-2"
    ],
    "generated": "R2 U2 R2 U' R2 U' R2"
  },
  {
    "id": 31,
    "group": "corner-in-slot",
    "setup": "F' U F2 R' F' R",
    "algorithms": [
      "R' F R F2 U' F"
    ],
    "fromDictionary": [],
    "generated": "R' F R F2 U' F"
  },
  {
    "id": 32,
    "group": "corner-in-slot",
    "setup": "F' U2 F R U2 R'",
    "algorithms": [
      "R U2 R' F' U2 F"
    ],
    "fromDictionary": [],
    "generated": "R U2 R' F' U2 F"
  },
  {
    "id": 33,
    "group": "corner-in-slot",
    "setup": "R U' R' U2 R U2 R'",
    "algorithms": [
      "U R U R' U' R U R'",
      "R U2 R' U2 R U R'"
    ],
    "fromDictionary": [
      "basic-paired-flip",
      "c11e00",
      "c01e10",
      "c31e10",
      "corner-in-slot-edge-ur",
      "edge-in-slot-corner-ubr",
      "edge-in-slot-corner-ufl",
      "separated-1",
      "separated-4"
    ],
    "generated": "R U2 R' U2 R U R'"
  },
  {
    "id": 34,
    "group": "corner-in-slot",
    "setup": "R U R' U' R U R'",
    "algorithms": [
      "R U' R' U R U' R'"
    ],
    "fromDictionary": [
      "c20e30",
      "c21e10",
      "c10e00",
      "c01e20",
      "corner-in-slot-edge-ub",
      "edge-in-slot-corner-ufr",
      "edge-in-slot-corner-ubl",
      "separated-2"
    ],
    "generated": "R U' R' U R U' R'"
  },
  {
    "id": 35,
    "group": "corner-in-slot",
    "setup": "F' U F U2 R U2 R'",
    "algorithms": [
      "R U2 R' U2 F' U' F"
    ],
    "fromDictionary": [],
    "generated": "R U2 R' U2 F' U' F"
  },
  {
    "id": 36,
    "group": "corner-in-slot",
    "setup": "R U' R2 U2 R2 U R2 U R",
    "algorithms": [
      "R' U' R2 U' R2 U2 R2 U R'"
    ],
    "fromDictionary": [],
    "generated": "R' U' R2 U' R2 U2 R2 U R'"
  },
  {
    "id": 37,
    "group": "both-in-slot",
    "setup": "R F U R U' R' F' U' R'",
    "algorithms": [
      "R U F R U R' U' F' R'"
    ],
    "fromDictionary": [],
    "generated": "R U F R U R' U' F' R'"
  },
  {
    "id": 38,
    "group": "both-in-slot",
    "setup": "R2 U2 R' U' R U' R' U2 R'",
    "algorithms": [
      "R U' R' U R U2 R' U R U' R'",
      "R U2 R U R' U R U2 R2"
    ],
    "fromDictionary": [
      "c11e20",
      "c31e00",
      "edge-flip-1",
      "slot-wrong-ori-1"
    ],
    "generated": "R U2 R U R' U R U2 R2"
  },
  {
    "id": 39,
    "group": "both-in-slot",
    "setup": "R U F R U R' U' F' R'",
    "algorithms": [
      "R F U R U' R' F' U' R'"
    ],
    "fromDictionary": [],
    "generated": "R F U R U' R' F' U' R'"
  },
  {
    "id": 40,
    "group": "both-in-slot",
    "setup": "R2 U2 F R2 F' U2 R' U R'",
    "algorithms": [
      "R U' R U2 F R2 F' U2 R2"
    ],
    "fromDictionary": [],
    "generated": "R U' R U2 F R2 F' U2 R2"
  },
  {
    "id": 41,
    "group": "both-in-slot",
    "setup": "R U2 R U R' U R U2 R2",
    "algorithms": [
      "R2 U2 R' U' R U' R' U2 R'"
    ],
    "fromDictionary": [],
    "generated": "R2 U2 R' U' R U' R' U2 R'"
  }
]
